# Please see the documentation for all configuration options:
# https://docs.github.com/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file

version: 2
updates:
  - package-ecosystem: 'npm'
    directory: '/' # Root folder
    schedule:
      interval: 'weekly'
    open-pull-requests-limit: 5
    commit-message:
      prefix: 'Deps:' # Dependency name in the commit message
    labels:
      - 'dependencies'
    ignore:
      - dependency-name: 'expo'
        update-types: ['version-update:semver-major']
      - dependency-name: 'expo-*'
      - dependency-name: 'react'
        update-types: ['version-update:semver-major']
      - dependency-name: 'react-dom'
        update-types: ['version-update:semver-major']
      - dependency-name: 'react-native'
        update-types: ['version-update:semver-major']
      - dependency-name: '@types/react'
        update-types: ['version-update:semver-major']
      - dependency-name: 'expo-router'
        update-types: ['version-update:semver-major']
  - package-ecosystem: 'github-actions'
    directory: '/'
    schedule:
      interval: 'weekly'
