// Full list of IANA timezones grouped by region
export const timeZonesByRegion = {
  Africa: [
    'Africa/Cairo',
    'Africa/Casablanca',
    'Africa/Johannesburg',
    'Africa/Lagos',
    'Africa/Nairobi',
    'Africa/Tunis',
  ],
  America: [
    'America/Anchorage',
    'America/Bogota',
    'America/Argentina/Buenos_Aires',
    'America/Caracas',
    'America/Chicago',
    'America/Denver',
    'America/Halifax',
    'America/Los_Angeles',
    'America/Mexico_City',
    'America/New_York',
    'America/Phoenix',
    'America/Santiago',
    'America/Sao_Paulo',
    'America/St_Johns',
    'America/Toronto',
    'America/Vancouver',
  ],
  Asia: [
    'Asia/Baghdad',
    'Asia/Bangkok',
    'Asia/Beirut',
    'Asia/Dubai',
    'Asia/Hong_Kong',
    'Asia/Jakarta',
    'Asia/Jerusalem',
    'Asia/Karachi',
    'Asia/Calcutta',
    'Asia/Kuwait',
    'Asia/Manila',
    'Asia/Riyadh',
    'Asia/Seoul',
    'Asia/Shanghai',
    'Asia/Singapore',
    'Asia/Taipei',
    'Asia/Tehran',
    'Asia/Tokyo',
    'Asia/Yangon',
  ],
  Atlantic: ['Atlantic/Azores', 'Atlantic/Cape_Verde', 'Atlantic/Reykjavik'],
  Australia: [
    'Australia/Adelaide',
    'Australia/Brisbane',
    'Australia/Darwin',
    'Australia/Melbourne',
    'Australia/Perth',
    'Australia/Sydney',
  ],
  Europe: [
    'Europe/Amsterdam',
    'Europe/Athens',
    'Europe/Belgrade',
    'Europe/Berlin',
    'Europe/Brussels',
    'Europe/Bucharest',
    'Europe/Budapest',
    'Europe/Copenhagen',
    'Europe/Dublin',
    'Europe/Helsinki',
    'Europe/Istanbul',
    'Europe/Kiev',
    'Europe/Lisbon',
    'Europe/London',
    'Europe/Madrid',
    'Europe/Moscow',
    'Europe/Oslo',
    'Europe/Paris',
    'Europe/Prague',
    'Europe/Rome',
    'Europe/Stockholm',
    'Europe/Vienna',
    'Europe/Warsaw',
    'Europe/Zurich',
  ],
  Indian: ['Indian/Maldives', 'Indian/Mauritius'],
  Pacific: [
    'Pacific/Auckland',
    'Pacific/Fiji',
    'Pacific/Guam',
    'Pacific/Honolulu',
    // TODO: Commented due to react-native (perhaps iOS) problems with support
    // "Pacific/Samoa",
    'Pacific/Tahiti',
  ],
};

export const timeZones = Object.values(timeZonesByRegion).flat().sort();
